name: calculadora_immc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: any

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/Home.jpg
    
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-VariableFont.ttf
